version: '3.8'

services:
  mysql-production:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: loans_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  mysql-warehouse:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: loans_warehouse
    ports:
      - "3306:3306"
    volumes:
      - mysql-warehouse-data:/var/lib/mysql

  generate-data:
    build:
      context: .
      dockerfile: Dockerfile_generate_data
    environment:
      MYSQL_PROD_HOST: mysql-production
      MYSQL_PROD_PORT: 3306
      MYSQL_PROD_USER: root
      MYSQL_PROD_PASSWORD: password
      MYSQL_PROD_DB: loans_db
    depends_on:
      - mysql-production

  etl-script:
    build:
      context: .
      dockerfile: Dockerfile_etl_script
    environment:
      MYSQL_PROD_HOST: mysql-production
      MYSQL_PROD_PORT: 3306
      MYSQL_PROD_USER: root
      MYSQL_PROD_PASSWORD: password
      MYSQL_PROD_DB: loans_db
      MYSQL_WAREHOUSE_HOST: mysql-warehouse
      MYSQL_WAREHOUSE_PORT: 3306
      MYSQL_WAREHOUSE_USER: root
      MYSQL_WAREHOUSE_PASSWORD: password
      MYSQL_WAREHOUSE_DB: loans_warehouse
    depends_on:
      - mysql-production
      - mysql-warehouse

  dbt:
    build:
      context: .
      dockerfile: Dockerfile_dbt
    environment:
      DBT_PROFILES_DIR: /app/dbt_project
      MYSQL_WAREHOUSE_HOST: mysql-warehouse
      MYSQL_WAREHOUSE_PORT: 3306
      MYSQL_WAREHOUSE_USER: root
      MYSQL_WAREHOUSE_PASSWORD: password
      MYSQL_WAREHOUSE_DB: loans_warehouse
    depends_on:
      - mysql-warehouse

volumes:
  mysql-data:
  mysql-warehouse-data: